datastax-java-driver {

  basic.contact-points = ["localhost:9042"]

  basic {
    load-balancing-policy {
      local-datacenter = "dc1"
    }
  }

  advanced.auth-provider {
    class = PlainTextAuthProvider
    username = cassandra
    password = cassandra
  }
}

