
datastax-java-driver {
  basic.contact-points = ["node-0.aws-us-west-2.156eed942de36cc4d89d.clusters.scylla.cloud:9042", "node-1.aws-us-west-2.156eed942de36cc4d89d.clusters.scylla.cloud:9042", "node-2.aws-us-west-2.156eed942de36cc4d89d.clusters.scylla.cloud:9042"]
  basic {
    load-balancing-policy {
      local-datacenter = AWS_US_WEST_2
    }
  }

  advanced.auth-provider {
    class = PlainTextAuthProvider
    username = scylla
    password = ohy5wZFTc8Jrtn3
  }
}
