
datastax-java-driver {
  basic {
    
    contact-points = [
    "node-0.gce-us-west-1.0006ab8f55853443c0fc.clusters.scylla.cloud:19042",
    "node-1.gce-us-west-1.0006ab8f55853443c0fc.clusters.scylla.cloud:19042",
    "node-2.gce-us-west-1.0006ab8f55853443c0fc.clusters.scylla.cloud:19042"
    ]
  
    load-balancing-policy {
      local-datacenter = GCE_US_WEST_1
      local-rack = us-west1-a
      slow-replica-avoidance = false 
    }
  }

  advanced {
    auth-provider {
      class = PlainTextAuthProvider
      username = scylla
      password = iBF7Iv46MtyfQdx
    }
    
    # Scylla Proxy + Shard-Per-Core
    protocol {
      max-schema-agreement-wait = 30 seconds
    }
    
    connection {
      connect-timeout = 15 seconds
      request-timeout = 30 seconds
    }
    
    pool {
      local.size = 4  # Scylla Cloud: more connections
      remote.size = 1
    }
    
    # SHARD AWARENESS - CRITICAL FOR SCYLLA CLOUD
    shard-awareness.policy.class = NodeShardAwareness
    shard-awareness.host-level-shard-count = 256  # Typical Scylla Cloud
  }
}
  
